rule:
  meta:
    name: access Kubernetes credentials
    namespace: collection/container/kubernetes
    authors:
      - maximemorin@google.com
    scopes:
      static: function
      dynamic: call
    att&ck:
      - Credential Access::Unsecured Credentials::Credentials In Files [T1552.001]
    references:
      - https://unit42.paloaltonetworks.com/teamtnt-operations-cloud-environments/
    examples:
      - ed40bce040778e2227c869dac59f54c320944e19f77543954f40019e2f2b0c35
  features:
    - or:
      - string: "/etc/eksctl/metadata.env"
