rule:
  meta:
    name: set environment variable
    namespace: host-interaction/environment-variable
    author: michael.hunhoff@mandiant.com
    scope: function
    mbc:
      - Operating System::Environment Variable::Set Variable [C0034.001]
    examples:
      - Practical Malware Analysis Lab 11-03.exe_:0x406580
  features:
    - or:
      - api: kernel32.SetEnvironmentStrings
      - api: kernel32.SetEnvironmentVariable
