name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rule_linter:
    runs-on: ubuntu-latest
    steps:
    # We check the submodules separately as the rules submodule's reference may not be our PR/master
    - name: Checkout capa without submodules
      uses: actions/checkout@v2
      with:
        repository: fireeye/capa
    - name: Checkout capa-rules
      uses: actions/checkout@v2
      with:
        path: rules
    - name: Checkout capa-testfiles
      uses: actions/checkout@v2
      with:
        repository: fireeye/capa-testfiles
        path: tests/data
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install capa
      run: pip install -e .
    # Regular lint is fast, so do this first
    - name: Run regular lint on all rules
      run: python scripts/lint.py rules/
    # Then run thorough lint
    - name: Get modified files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Run thorough lint on modified rule files
      run: |
        cd rules/
        for changed_file in ${{ steps.files.outputs.added_modified }} ${{ steps.files.outputs.renamed }}; do
          if [[ ! $changed_file =~ ".git" ]]; then
            tag=$(grep 'name:' $changed_file | sed 's/^.*: //')
            python ../scripts/lint.py --thorough -t "$tag" -v .
          fi
        done
  # Ensure that new rules are compatible with latest release
  rules_latest_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout capa-rules
      uses: actions/checkout@v2
      with:
        path: rules
    - name: Checkout capa-testfiles
      uses: actions/checkout@v2
      with:
        repository: fireeye/capa-testfiles
        path: tests/data
    - name: Get latest release executable name
      run: echo "zip_name=capa-$(curl -s https://api.github.com/repos/fireeye/capa/releases/latest |
                 jq .name |
                 tr -d '"')-linux.zip" >> $GITHUB_ENV
    - name: Fetch latest capa release executable
      uses: robinraju/release-downloader@v1
      with:
        repository: "fireeye/capa"
        latest: true
        fileName: ${{ env.zip_name }}
    - name: Unzip
      run: unzip ${{ env.zip_name }} -d latest-release
    - name: Run latest release with current rules
      run: latest-release/capa -r rules/ tests/data/9324d1a8ae37a36ae560c37448c9705a.exe_
